YaraAutoTestWeb/YARA_TEST/info/__init__.py
import logging
from logging.handlers import RotatingFileHandler
from flask import Flask
from config import config_dict


def setup_log(config_name):
    """记录日志的配置"""
    # 根据传入的配置字符串获取不配置
    configClass = config_dict[config_name]
    logging.basicConfig(level=configClass.LOG_LEVEL)
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    file_log_handler.setFormatter(formatter)
    logging.getLogger().addHandler(file_log_handler)


def create_app(config_name):
    """创建app方法,工厂方法"""
    # 0.记录日志
    setup_log(config_name)

    # 1.创建app对象
    app = Flask(__name__)

    # development -->DevelopmentConfig 开发模式的配置类
    # production --->ProductionConfig 线上模式的配置类
    configClass = config_dict[config_name]

    # 将配置类注册到app上 根据配置的不同类 赋予不用模式的app
    app.config.from_object(configClass)

    # 注册蓝图
    # 真正用到蓝图对象的时候才导入,延迟导入(只有函数被调用才回来导入) 解决循环导入问题
    # 注册首页的蓝图对象
    from info.core.index import index_bp
    app.register_blueprint(index_bp)

    from info.core.analysis_sample import analysis_sample_bp
    app.register_blueprint(analysis_sample_bp)


    from info.core.upload_yara import upload_yara_bp
    app.register_blueprint(upload_yara_bp)






    # 返回不同模式下的app对象
    return app

YaraAutoTestWeb/YARA_TEST/info/core/__init__.py
#项目是要分模块开发: 目前只有首页

YaraAutoTestWeb/YARA_TEST/info/core/analysis_sample/__init__.py
from flask import Blueprint

analysis_sample_bp = Blueprint("analysis_sample", __name__)

from .views import *

YaraAutoTestWeb/YARA_TEST/info/core/analysis_sample/views.py
# -*-coding:utf8-*-
import json

from . import analysis_sample_bp
from flask import request, render_template
from common.postfile_collect import submit
from common.get_submitres import get_submitlog
from common.analysis_status import status_query
from common.post_result import post_summary,post_details




# 投放样本
@analysis_sample_bp.route('/post', methods=['POST'])
def post():
    filepath = request.form.get("filepath")
    samplestype = request.form.get("samplestype")
    postret = submit(filepath, samplestype)
    return "1"


# #获取样本投放日志
@analysis_sample_bp.route('/getlog', methods=['GET'])
def getlog():
    submit_log = get_submitlog()
    return render_template(
        'log.html',
        log=submit_log,
    )


# 获取样本检测结果日志
@analysis_sample_bp.route('/getresult/<result>', methods=['GET'])
def getresult(result):
    status = status_query()
    if result == "all_black":
        summary = post_summary("black")
        return render_template("result_black.html",log=summary,status=status)

    elif result == "all_white":
        summary = post_summary("white")
        return render_template("result_white.html",log=summary,status=status)

    else:
        urlcrack_data = result.split("_")
        submit_date = urlcrack_data[0]
        check_type = urlcrack_data[1]
        judge = urlcrack_data[2]
        return render_template("details.html",details=json.dumps(post_details(submit_date, check_type, judge), ensure_ascii=False,indent=4))

YaraAutoTestWeb/YARA_TEST/info/core/index/__init__.py
from flask import Blueprint

# 创建蓝图对象
index_bp = Blueprint("index", __name__)

# 导入views中的视图函数
from .views import *

YaraAutoTestWeb/YARA_TEST/info/core/index/views.py
# -*-coding:utf8-*-
from . import index_bp
from flask import render_template
from wtforms import StringField
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired





# 使用蓝图
@index_bp.route("/", methods=['GET'])
def home():
    form = QueryForm()
    return render_template('index.html', form=form)


class QueryForm(FlaskForm):
    filepath = StringField(u'文件上传路径', validators=[DataRequired()])

YaraAutoTestWeb/YARA_TEST/info/core/upload_yara/__init__.py
from flask import Blueprint

upload_yara_bp = Blueprint("upload_yara", __name__)


from .views import *

YaraAutoTestWeb/YARA_TEST/info/core/upload_yara/views.py
# -*-coding:utf8-*-
from flask import render_template, request
import os
from time import ctime
from . import upload_yara_bp
from werkzeug.utils import secure_filename
from common.check_yara_format import check_Yara_Format
from common.analysis_status import status_query
from common.tmp_rule import add2analyse
from common.config import Config

cfg = Config()

if not os.path.exists("/home/YaraAutoTestWeb/YARA_TEST/uploads2lib"):
    os.mkdir("/home/YaraAutoTestWeb/YARA_TEST/uploads2lib")
if not os.path.exists("/home/YaraAutoTestWeb/YARA_TEST/uploads2judge"):
    os.mkdir("/home/YaraAutoTestWeb/YARA_TEST/uploads2judge")
if not os.path.exists("/home/YaraAutoTestWeb/YARA_TEST/uploads2analyse"):
    os.mkdir("/home/YaraAutoTestWeb/YARA_TEST/uploads2analyse")

curdir = os.path.dirname(os.path.realpath(__file__))
yarajudge = check_Yara_Format()


def allowed_file(filename):
    ALLOWED_EXTENSIONS = cfg.config_path.allowed_extensions
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS


@upload_yara_bp.route('/yara', methods=['GET'])
def yarahome():
    return render_template('yaraindex.html')


# 上传入库文件
@upload_yara_bp.route('/uploads2lib', methods=['POST'])
def uploads2lib():
    uploaded_files = request.files.getlist("file[]")
    savetime = "_".join(ctime().split(" ")).replace(":", "_")
    savedir = os.path.join(cfg.config_path.upload_folder_2lib, savetime)
    if not os.path.exists(savedir):
        os.mkdir(savedir)

    filenames = []
    ret = ""
    for file in uploaded_files:
        filename = secure_filename(file.filename)
        filepath = os.path.join(curdir, savedir, filename)
        file.save(filepath)
        if file and allowed_file(file.filename):
            p = os.popen("curl {0} -F f=@{1}".format(cfg.config_path.yaralib, filepath))
            ret = p.read()
            p.close()

            if ret.find("success") != -1:
                filenames.append((savetime, filename, "successed!"))
            if ret.find("false") != -1:
                filenames.append((savetime, filename, "failed! check network status please!"))
        else:
            filenames.append((savetime, filename, "failed! unsupport file type"))
    return render_template('libupload.html', filenames=filenames)


# 上传校验文件
@upload_yara_bp.route('/uploads2judge', methods=['POST'])
def uploads2judge():
    uploaded_files = request.files.getlist("file[]")
    savetime = "_".join(ctime().split(" ")).replace(":", "_")
    savedir = os.path.join(cfg.config_path.upload_folder_2judge, savetime)
    if not os.path.exists(savedir):
        os.mkdir(savedir)

    allright_status = 1
    filenames = []
    ret = ""
    # senmail
    qqmail = request.values.get('qqmail', "")
    if not qqmail:
        return "Please enter your qq mail!"

    for file in uploaded_files:
        filename = secure_filename(file.filename)
        filepath = os.path.join(curdir, savedir, filename)
        file.save(filepath)
        if file and allowed_file(file.filename):
            res = yarajudge.check_yara_format(filepath, savetime)
            if res[0]:
                filenames.append((savetime, filename, "ok"))
            elif len(res) == 4:
                filenames.append((savetime, filename, "{0}:{1}".format(res[2], res[1])))
                allright_status = 0
            else:
                filenames.append((savetime, filename, res[1]))
                allright_status = 0
        else:
            filenames.append((savetime, filename, "unsupport file type, yara or yar file"))
            allright_status = 0
    status = status_query()
    if allright_status:
        add2analyse(savedir, qqmail)
    return render_template('judgeupload.html', filenames=filenames, status=status)

YaraAutoTestWeb/YARA_TEST/info/templates/base.html
<!DOCTYPE html>
<html>
<head>
   <!-- <meta charset="UTF-8"> -->
   <!-- <meta http-equiv="Content-Type" content="text/json"> -->
   <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
   <title>{% block title%}Yara误报批量测试{% endblock %}</title>
   <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">
      <script src="{{url_for('static', filename='js/jquery-1.7.2.min.js')}}"></script>
      <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h1><a href="{{url_for('index.home')}}">Yara误报批量测试</a></h1>
            <p>1、误报测试依赖沙箱分析;</p>
            <p>2、误报测试结果会自动推送后台配置的邮箱</p>
            <p>3、一般情况为<a href="http://172.31.50.39:8081/yara">提交新的yara规则</a>后进行误报测试</p>
        </div>
        {% block body %}
        {% endblock %}
    </div>
 
</body>
</html>

YaraAutoTestWeb/YARA_TEST/info/templates/details.html
{% extends "base.html" %}
{% block body %}
<pre>{{details}}</pre>
{% endblock %}

YaraAutoTestWeb/YARA_TEST/info/templates/index.html
{% extends "base.html" %}
{% block body %}

<script src="{{url_for('static', filename='js/post.js')}}" type="text/javascript"></script>

<div class="col-lg-12">
  <form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
      {{form.filepath.label}}
      {% if form.filepath.errors %}
        {% for e in form.filepath.errors %}
          <p class="help-block">{{e}}</p>
        {% endfor %}
      {% endif %}
      {{form.filepath(class_="form-control")}}
    </div>
    <p style="color:blue">注:将样本批量上传服务器 给出样本所在路径 eg."/home/zhuqing/samples"</p>
    

    <input class="btn btn-primary" type="button" onclick="postfile()" value="上传文件" id='post'>
    &nbsp;
    &nbsp;
    <input class="btn btn-primary" type="button" onclick="javascript:window.open('/getlog');"  value="查看日志" id='getlog'>
    <input class="btn btn-primary" type="button" onclick="javascript:window.open('/getresult/all_black');"  value="查看检出结果" id='getblackresult'>
    <input class="btn btn-primary" type="button" onclick="javascript:window.open('/getresult/all_white');"  value="查看误报结果" id='getwhiteresult'>
  </form>



</div>

<div class="col-lg-12">
<p style="font-weight:bold">选择样本类型</p>
<select id="select_samplestype">
<!-- <option value="none">选择样本类型</option> -->
<option value="black">黑样本</option>
<option value="white">白样本</option>
</select>
</div>
{% endblock %}

YaraAutoTestWeb/YARA_TEST/info/templates/judgeupload.html
{% extends "yarabase.html" %}
{% block body %}

<div class="container">
  <ul>
   {% for file in filenames %}
    <li style="color:#337ab7;font-size:15px;">{{file[1]}}------{{file[2]}}</li>
   {% endfor %}
  </ul>
  <!-- {% if status %}
    <li style="color:#337ab7;font-size:15px;">解析程序正在执行,待样本解析完后再提交规则</li>
  {% endif %} -->
</div>
{% endblock %}

YaraAutoTestWeb/YARA_TEST/info/templates/libupload.html
{% extends "yarabase.html" %}
{% block body %}

<div class="container">
  <ul>
   {% for file in filenames %}
    <li style="color:#337ab7;font-size:15px;">{{file[1]}}------{{file[2]}}</li>
   {% endfor %}
  </ul>
</div>
{% endblock %}

YaraAutoTestWeb/YARA_TEST/info/templates/log.html
{% extends "base.html" %}
{% block body %}
{% if log %}
  <div class="col-lg-10">
      <table class="log" border = "1"; style="margin-left:-22px;width: 1150px; table-layout: fixed; word-wrap: break-word;">
        <tr style="font-size:15px">
            <th style="text-align:center">投放样本时间</th>
            <th style="text-align:center">投放样本状态</th>
            <th style="text-align:center">样本黑白属性</th>
            <th style="text-align:center">投放样本总数</th>
            <th style="text-align:center">提交失败总数</th>
        </tr>    
        {% for item in log %}
          <tr style="text-align:center">
            <td>{{item.submit_date}}</td>
            <td>{{item.submit_status}}</td>
            <td>{{item.samlpes_type}}
            {% if "total_count" in item%}
              <td>{{item.total_count}}</td>
              <td>{{item.fail_count}}</td>
            {% else %}
              <td>正在投放样本</td>
              <td>正在投放样本</td>
            {% endif %}
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endif %}
{% endblock %}

YaraAutoTestWeb/YARA_TEST/info/templates/result_black.html
{% extends "base.html" %}
{% block body %}
<style type="text/css">
  .a-btn{
    border:none;
    background: none;
    color:#337ab7;
  }
  .a-btn:hover{
    text-decoration: underline;
  }
  .a-btn:focus{
    outline: none;
  }

  .ban{
    cursor:not-allowed;
    color:#cccccc;

  }
  .ban:hover{
    text-decoration: none;
  }
</style>
  <script type="text/javascript" src="{{url_for('static', filename='js/reanalysis.js')}}"></script>
  <div class="col-lg-10">
    <p style="font-size:15px;margin-left:-122px">检出样本统计:</p>
    <table class="result" border="1" style="margin-left:-122px;width: 1350px;word-wrap:break-word;">
      <tr style="font-size:15px;">
          <th style="text-align:center">投放样本时间</th>
          <th style="text-align:center">重解析开始时间</th>
          <th style="text-align:center">解析结束时间</th>
          <th style="text-align:center">投放样本总数</th>
          <th style="text-align:center">YARA检出率</th>
          <th style="text-align:center">解析状态</th>
      </tr>
      {% if log %}
          {% for item in log %}
          <tr style="text-align: center">
            <td>{{item.sumbit_date}}</td>
            <td>{{item.reanalysis_starttime}}</td>
            <td>{{item.analysis_date}}</td>
            <td>{{item.total_count}}</td>
            <td><a href="/getresult/{{item.sumbit_date}}_yara_black">{{item.yara.yara_percent}} ({{item.yara.yara_count}})</a></td>
            {% if item.sumbit_date in status%}
              <td>正在重新解析</td>
            {% else %}
              <td>等待重新解析</td>
            {% endif %}
          </tr>
          {% endfor %}
      {% endif %} 
    </table>
  </div>

<!--   <input class="btn btn-primary" style="margin-left:1128px; margin-top:20px;" type="button" value="一键全部重解析" onclick="reanalysisall(this.id)" id="reanalysisall_black"> -->
{% endblock %}

YaraAutoTestWeb/YARA_TEST/info/templates/result_white.html
{% extends "base.html" %}
{% block body %}
<style type="text/css">
  .a-btn{
    border:none;
    background: none;
    color:#337ab7;
  }
  .a-btn:hover{
    text-decoration: underline;
  }
  .a-btn:focus{
    outline: none;
  }

  .ban{
    cursor:not-allowed;
    color:#cccccc; 

  }
  .ban:hover{
    text-decoration: none;
  }
</style>
  <script type="text/javascript" src="{{url_for('static', filename='js/reanalysis.js')}}"></script>
  <div class="col-lg-10">
    <p style="font-size:15px;margin-left:-122px">误报样本统计:</p>
    <table class="result" border="1" style="margin-left:-122px;width: 1350px;word-wrap:break-word;">
      <tr style="font-size:15px;">
          <th style="text-align:center">投放样本时间</th>
          <th style="text-align:center">重解析开始时间</th>
          <th style="text-align:center">解析结束时间</th>
          <th style="text-align:center">投放样本总数</th>
          <th style="text-align:center">YARA误报率</th>
          <th style="text-align:center">解析状态</th>
      </tr>
      {% if log %}
          {% for item in log %}
          <tr style="text-align: center">
            <td>{{item.sumbit_date}}</td>
            <td>{{item.reanalysis_starttime}}</td>
            <td>{{item.analysis_date}}</td>
            <td>{{item.total_count}}</td>
            <td><a href="/getresult/{{item.sumbit_date}}_yara_white">{{item.yara.yara_percent}} ({{item.yara.yara_count}})</a></td>
            <!-- <td><button class='a-btn' id = {{item.submit_date}} onclick="reanalysis(this.id)">重新解析</button></td> -->
            {% if item.sumbit_date in status%}
              <td>正在重新解析</td>
            {% else %}
              <td>等待重新解析</td>
            {% endif %}
          </tr>
          {% endfor %}
      {% endif %} 
    </table>
  </div>
  <!-- <input class="btn btn-primary" style="margin-left:1128px; margin-top:20px;" type="button" value="一键全部重解析" onclick="reanalysisall(this.id)" id="reanalysisall_white"> -->
{% endblock %}

YaraAutoTestWeb/YARA_TEST/info/templates/yarabase.html
<!DOCTYPE html>
<html>
<head>
   <!-- <meta charset="UTF-8"> -->
   <!-- <meta http-equiv="Content-Type" content="text/json"> -->
   <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport">
   <title>{% block title%}Yara规则校验及入库{% endblock %}</title>
   
   <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}">
      <script src="{{url_for('static', filename='js/jquery-1.7.2.min.js')}}"></script>
      <script src="{{url_for('static', filename='js/bootstrap.min.js')}}"></script>
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h1><a href="{{url_for('upload_yara.yarahome')}}">Yara规则校验及入库</a></h1>
        <p>注意事项：</p>
	    <p>1、支持yar和yara后缀的文件上传;</p>
        <p>2、yara规则文件校验全部通过后会自动更新到待测试后台目录</p>
        <p>3、如果批量提交的规则部分校验不通过,则该批规则不会更新到沙箱分析后台,且不会自动进行误报测试;</p>
        <p>4、自动化测试在每周星期六凌晨1点进行</p>
	<p>5、如果分批上传的话 目前默认使用第一次输入的邮箱 后续会改进</p>
        <p>6、确认准确无误不需要进行误报测试的规则可以直接入库,请谨慎操作;</p>
        <p>7、<a href="http://172.31.50.46:5204/#/black/yara">规则库地址</a></p>
        </div>
        {% block body %}
        {% endblock %}
    </div>
 
</body>
</html>

YaraAutoTestWeb/YARA_TEST/info/templates/yaraindex.html
{% extends "yarabase.html" %}
{% block body %}
<style>
        .file {
            position: relative;
            
            overflow: hidden;
            
            text-decoration: none;
            text-indent: 0;
            line-height: 20px;
            cursor: pointer;
        }
        .file input {
            position: absolute;
            font-size: 100px;
            right: 0;
            top: 0;
            opacity: 0;
            cursor: pointer;
        }
        
#list{
	margin-top:20px;
	list-style:none
}
</style>


<div class="col-lg-12">
  <form method="post" action="uploads2judge" enctype="multipart/form-data">
    
  <a  class="btn btn-primary file">选择校验文件
    <input type="file" id = "file2" name="file[]" multiple="">
  </a>
<input type="text" name="qqmail" placeholder="QQ邮箱" class="input_txt">

  <a  class="btn btn-primary file">上传校验文件
     <input type="submit">
  </a>
   
  </form> 

  <form method="post" action="uploads2lib" enctype="multipart/form-data">
    
  <a  class="btn btn-primary file">选择入库文件
    <input type="file" id = "file1" name="file[]" multiple="">
  </a>
  <a  class="btn btn-primary file">上传入库文件
     <input type="submit">
  </a>
   
  </form>

</div>

<ul id="list">
</ul>
<script>
  var filelib=document.getElementById("file1");
      filelib.onchange=function () {
          var files=filelib.files,
              list=document.getElementById("list"),
              content="";
          for(var i=0;i<files.length;++i){
              content+=`<li>${files[i].name}</li>`
          }
          list.innerHTML="<p>已选择下列入库文件:</p>"+content;
      }
  var filejudge=document.getElementById("file2");
      filejudge.onchange=function () {
          var files=filejudge.files,
              list=document.getElementById("list"),
              content="";
          for(var i=0;i<files.length;++i){
              content+=`<li>${files[i].name}</li>`
          }
          list.innerHTML="<p>已选择下列校验文件:</p>"+content;
      }
</script>

{% endblock %}